import { useState, useRef, useMemo, useCallback } from 'react';
import { Download, Share2, FileText, FileDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { useTrades } from '@/hooks/useTrades';
import { useUserXP, getLevelFromXP } from '@/hooks/useGamification';
import { useProfile } from '@/hooks/useProfile';
import { calcPortfolioStats } from '@/lib/analytics';

type DateRange = '7d' | '30d' | '90d' | 'all';

export default function ExportSection() {
  const [open, setOpen] = useState(false);
  const [range, setRange] = useState<DateRange>('30d');
  const [generating, setGenerating] = useState(false);
  const { data: trades = [] } = useTrades();
  const { data: xp } = useUserXP();
  const { data: profile } = useProfile();
  const cardRef = useRef<HTMLDivElement>(null);

  const filteredTrades = useMemo(() => {
    if (range === 'all') return trades;
    const days = range === '7d' ? 7 : range === '30d' ? 30 : 90;
    const cutoff = new Date();
    cutoff.setDate(cutoff.getDate() - days);
    return trades.filter(t => new Date(t.createdAt) >= cutoff);
  }, [trades, range]);

  const stats = useMemo(() => calcPortfolioStats(filteredTrades), [filteredTrades]);
  const level = getLevelFromXP(xp?.totalXp ?? 0);
  const rangeLabel = range === '7d' ? 'Last 7 Days' : range === '30d' ? 'Last 30 Days' : range === '90d' ? 'Last 90 Days' : 'All Time';

  const generateCSV = useCallback(() => {
    const headers = ['Date', 'Pair', 'Direction', 'Entry', 'SL', 'TP', 'Lot Size', 'Risk %', 'R:R', 'Result', 'P/L'];
    const rows = filteredTrades.map(t => [
      new Date(t.createdAt).toLocaleDateString(),
      t.pair, t.direction, t.entryPrice, t.stopLoss, t.takeProfit,
      t.lotSize, t.riskPercent, t.rrRatio, t.result, t.profitLossAmount,
    ]);

    const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `trading-report-${range}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }, [filteredTrades, range]);

  const addFooter = (doc: any, pageW: number) => {
    doc.setFillColor(0, 191, 166);
    doc.rect(0, 289, pageW, 3, 'F');
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by PrecisionFlow  •  precisionflow.app', 14, 287);
    doc.text(`Page ${doc.internal.getNumberOfPages()}`, pageW - 28, 287);
  };

  const generatePDF = useCallback(async () => {
    setGenerating(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({ unit: 'mm', format: 'a4' });
      const name = profile?.displayName || 'Trader';
      const pageW = doc.internal.pageSize.getWidth();

      // Load logo
      try {
        const logoUrl = new URL('/src/assets/smc-log-logo.png', window.location.origin).href;
        const resp = await fetch(logoUrl);
        const blob = await resp.blob();
        const reader = new FileReader();
        const logoData: string = await new Promise((res) => {
          reader.onloadend = () => res(reader.result as string);
          reader.readAsDataURL(blob);
        });
        doc.addImage(logoData, 'PNG', 14, 8, 18, 18);
      } catch { /* logo load failed, continue without */ }

      // Branded header bar
      doc.setFillColor(0, 191, 166); // teal primary
      doc.rect(0, 0, pageW, 4, 'F');

      // Title next to logo
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(30, 30, 30);
      doc.text('PrecisionFlow', 35, 17);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text('Trading Performance Report', 35, 23);

      // Subtitle
      doc.setFontSize(9);
      doc.setTextColor(130, 130, 130);
      doc.text(`${name}  •  ${rangeLabel}  •  Level: ${level.name}  •  ${new Date().toLocaleDateString()}`, 14, 32);

      // Teal divider
      doc.setDrawColor(0, 191, 166);
      doc.setLineWidth(0.5);
      doc.line(14, 35, pageW - 14, 35);

      // Key Metrics section
      doc.setFontSize(13);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(30, 30, 30);
      doc.text('Key Metrics', 14, 43);

      const metrics = [
        ['Win Rate', `${stats.winRate}%`],
        ['Total R', `${stats.totalR > 0 ? '+' : ''}${stats.totalR}R`],
        ['Profit Factor', `${stats.profitFactor}`],
        ['Expectancy', `${stats.expectancy}R`],
        ['Total Trades', `${stats.closed.length}`],
        ['Wins / Losses', `${stats.closed.filter(t => t.result === 'win').length} / ${stats.closed.filter(t => t.result === 'loss').length}`],
      ];

      let y = 50;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      metrics.forEach(([label, value], i) => {
        // Alternating row background
        if (i % 2 === 0) {
          doc.setFillColor(245, 247, 250);
          doc.rect(14, y - 4, pageW - 28, 7, 'F');
        }
        doc.setTextColor(100, 100, 100);
        doc.text(label, 16, y);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(30, 30, 30);
        doc.text(value, 80, y);
        doc.setFont('helvetica', 'normal');
        y += 7;
      });

      // Trade Log
      y += 8;
      doc.setFontSize(13);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(30, 30, 30);
      doc.text('Trade Log', 14, y);
      y += 8;

      // Table header with teal background
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255, 255, 255);
      doc.setFillColor(0, 191, 166);
      doc.roundedRect(14, y - 4, pageW - 28, 6, 1, 1, 'F');
      const cols = ['Date', 'Pair', 'Dir', 'Entry', 'SL', 'TP', 'Lot', 'R:R', 'Result', 'P/L'];
      const colX = [15, 35, 55, 67, 82, 97, 112, 125, 140, 160];
      cols.forEach((col, i) => doc.text(col, colX[i], y));
      y += 5;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      filteredTrades.slice(0, 50).forEach((t, i) => {
        if (y > 275) {
          // Footer on current page
          addFooter(doc, pageW);
          doc.addPage();
          y = 20;
        }
        if (i % 2 === 0) {
          doc.setFillColor(248, 250, 252);
          doc.rect(14, y - 3.5, pageW - 28, 5, 'F');
        }
        const isWin = t.result === 'win';
        doc.setTextColor(60, 60, 60);
        doc.text(new Date(t.createdAt).toLocaleDateString(), colX[0], y);
        doc.text(t.pair, colX[1], y);
        doc.text(t.direction, colX[2], y);
        doc.text(String(t.entryPrice), colX[3], y);
        doc.text(String(t.stopLoss), colX[4], y);
        doc.text(String(t.takeProfit), colX[5], y);
        doc.text(String(t.lotSize), colX[6], y);
        doc.text(String(t.rrRatio), colX[7], y);
        // Color-coded result
        doc.setTextColor(isWin ? 0 : 211, isWin ? 200 : 47, isWin ? 83 : 47);
        doc.text(t.result.toUpperCase(), colX[8], y);
        doc.setTextColor(isWin ? 0 : 211, isWin ? 200 : 47, isWin ? 83 : 47);
        doc.text(String(t.profitLossAmount), colX[9], y);
        y += 5;
      });

      addFooter(doc, pageW);
      doc.save(`PrecisionFlow-Report-${range}.pdf`);
    } catch (e) {
      console.error('PDF generation failed:', e);
    } finally {
      setGenerating(false);
    }
  }, [filteredTrades, range, stats, profile, level, rangeLabel]);

  const handleShare = async () => {
    const text = `📊 My ${range === 'all' ? 'All-Time' : range.toUpperCase()} Trading Performance\n\n` +
      `Win Rate: ${stats.winRate}%\n` +
      `Total R: ${stats.totalR}R\n` +
      `Profit Factor: ${stats.profitFactor}\n` +
      `Trades: ${stats.closed.length}\n` +
      `Level: ${level.name}\n\n` +
      `Tracked with PrecisionFlow 📱`;

    if (navigator.share) {
      try {
        await navigator.share({ title: 'My Trading Performance', text });
      } catch { /* user cancelled */ }
    } else {
      await navigator.clipboard.writeText(text);
    }
  };

  return (
    <>
      <Button
        variant="ghost"
        size="icon"
        onClick={() => setOpen(true)}
        className="h-8 w-8"
      >
        <Download className="h-4 w-4" />
      </Button>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-w-sm max-h-[85vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-primary" />
              Export & Share
            </DialogTitle>
          </DialogHeader>

          {/* Date Range */}
          <div className="flex gap-2">
            {(['7d', '30d', '90d', 'all'] as DateRange[]).map(r => (
              <button
                key={r}
                onClick={() => setRange(r)}
                className={`flex-1 py-1.5 text-xs font-medium rounded-lg transition-colors ${
                  range === r
                    ? 'bg-primary text-primary-foreground'
                    : 'bg-secondary/50 text-muted-foreground'
                }`}
              >
                {r === 'all' ? 'All' : r.toUpperCase()}
              </button>
            ))}
          </div>

          {/* Snapshot Card */}
          <div ref={cardRef} className="glass-card p-4 space-y-3">
            <div className="flex items-center justify-between">
              <div>
                <p className="font-semibold text-foreground text-sm">{profile?.displayName || 'Trader'}</p>
                <p className="text-[10px] text-muted-foreground">{rangeLabel} Performance</p>
              </div>
              <span className="text-xs bg-primary/20 text-primary px-2 py-0.5 rounded-full font-medium">
                {level.name}
              </span>
            </div>
            <div className="grid grid-cols-2 gap-2 text-center">
              <div className="bg-secondary/50 rounded-lg p-2">
                <p className="text-lg font-bold text-foreground">{stats.winRate}%</p>
                <p className="text-[9px] text-muted-foreground">Win Rate</p>
              </div>
              <div className="bg-secondary/50 rounded-lg p-2">
                <p className={`text-lg font-bold ${stats.totalR >= 0 ? 'text-success' : 'text-loss'}`}>
                  {stats.totalR > 0 ? '+' : ''}{stats.totalR}R
                </p>
                <p className="text-[9px] text-muted-foreground">Total R</p>
              </div>
              <div className="bg-secondary/50 rounded-lg p-2">
                <p className="text-lg font-bold text-foreground">{stats.profitFactor}</p>
                <p className="text-[9px] text-muted-foreground">Profit Factor</p>
              </div>
              <div className="bg-secondary/50 rounded-lg p-2">
                <p className="text-lg font-bold text-foreground">{stats.closed.length}</p>
                <p className="text-[9px] text-muted-foreground">Trades</p>
              </div>
            </div>
            <p className="text-[8px] text-muted-foreground text-center">Tracked with PrecisionFlow</p>
          </div>

          {/* Actions */}
          <div className="grid grid-cols-3 gap-2">
            <Button variant="outline" onClick={generateCSV} className="gap-1.5 text-xs">
              <Download className="h-3.5 w-3.5" />
              CSV
            </Button>
            <Button variant="outline" onClick={generatePDF} disabled={generating} className="gap-1.5 text-xs">
              <FileDown className="h-3.5 w-3.5" />
              {generating ? '...' : 'PDF'}
            </Button>
            <Button onClick={handleShare} className="gap-1.5 text-xs">
              <Share2 className="h-3.5 w-3.5" />
              Share
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
